### ISSUE TITLE
All iOS images disappear when using Xamarin.Judopay 5.0.4

### ISSUE THREAD

**Issue by xleon** [Judopay/Xamarin-Sample-App#27]
We use xcassets (ImageAsset) for all images in the project.
As soon as we upgrade to version 5.0.4, they disappear from the app, even the app icon. 
It goes back to normal with 5.0.3, which took me almost 2 days to find out 😞
Hard to see if you don´t clean up the project first. 

It doesn´t happen with BundleResources at the "Resource" folder though. 

To reproduce it:
- Use Xamarin.Judopay 5.0.4
- Use an image asset in an asset catalog (xcassets)
- Clean up the iOS project
- Run the app (simulator or device)
- The image from the catalog is missing

**Comment by zfoltin** [comment]
Hey @xleon, is the issue on Windows or on a Mac? Could you give it a go with the latest 5.1 release please?

**Comment by zfoltin** [comment]
Hi @xleon 

It's an interesting one as in version 5.0.2 I moved the image assets in the iOS SDK into an Asset Catalog (xcasset) from Resources as it's the recommended way to embed images since iOS 9.
Then there is https://forums.xamarin.com/discussion/63222/class-library-asset-catalogs-overriding-app-asset-catalogs (also see the comments about AppVeyor (building on Windows) https://xamarin.github.io/bugzilla-archives/34/34762/bug.html - hence the latest releases are built on a Mac.
The only change between 5.0.3 and 5.0.4 was just a little update to the security label text size (and some unrelated dependency updates) so not sure what is causing this issue, unless it's still to do with the Xamarin/VS asset merging issue.

I'll try and find a solution, please bear with me.

**Comment by xleon** [comment]
Hi @zfoltin 

Did you change the iOS target version?

According to the links you provided this is a known issue. Guys are saying there that it can be solved by not using asset catalog in the library, but only in the app. 
How many assets do you have in there? Should we try that? (I would try the other way around, but have probably more than 100 assets...)

**Comment by zfoltin** [comment]
Hi @xleon 

I haven't tried the iOS target version but setting it to 6 isn't really appealing nor seems to be possible with the latest VS.

Pre 5.0.2 the SDK was using BundleResources which meant all our icons were missing. We don't have a ton, just the card icons (front and back where the cvv is). These are in an `Icons.xcassets` folder in the iOS SDK and they show up all right in the sample project now. Not quite sure yet why this would cause the disappearance of the hosting app's xcassets and what the workaround would be.

As you saw the issue has been known since 2015, interestingly with `Importance: "Low enhancement"` 😢 I'd really not like a solution to ask merchants to embed a set of images in their apps if they wanted the card images - that's the last resort if I can't find any other workarounds..
It's a shame MS treat this issue like this 😞

**Comment by zfoltin** [comment]
Another interesting read from 4 years ago - https://xamarin.github.io/bugzilla-archives/29/29016/bug.html
So I'll try and make these images BundleResource again and see if that somehow solves the issue (maybe with a custom renderer). If not, I'll remove the `xcassets` from the iOS SDK and put it in the sample app and update the Wiki with instructions about how to embed these in the client app.

**Comment by zfoltin** [comment]
Hey @xleon 
I've moved the images back to BundleResource on iOS. Could you give a go to the latest 5.1.3 version to see if this resolves the issue?

**Comment by xleon** [comment]
It works!
However it´s a bit disappointing that xamarin had this bug since a long time ago, as having assets in a library seems like a very common thing. Thanks for the update
